### ISSUE TITLE
It there any documentation exists ?

### ISSUE THREAD

**Issue by NetLancer** [radphp/radphp#7]
Or maybe forthcoming, sounds like a too dummy question but i haven't fount any sort of instructions there

**Comment by omid** [comment]
Hi,

You are right, we didn't write documentation for everything.
But you can use and check the app skeleton repository: https://github.com/radphp/app

Regards,
Omid

**Comment by NetLancer** [comment]
Let me try, hope there's some work going on on docs, usage samples etc. Nice titled project, Thanks though ))
